[mypy]
# disable_error_code = import-untyped

# [mypy-untyped_package.*]
# follow_untyped_imports = True

# [mypy-yklibpy.common.*]
# ignore_missing_imports = True

# [mypy-yklibpy.*]
# ignore_missing_imports = True
